name: PR Unit Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # You can use 'temurin', 'zulu', 'adopt', etc.

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test