name: Upload Logstash Core JAR

on:
  pull_request:

jobs:
  upload-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload Logstash Core JAR
        uses: actions/upload-artifact@v4
        with:
          name: logstash-core-jar
          path: ./logstash-core.jar